# Generated by Django 4.2.3 on 2023-07-25 19:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay', models.IntegerField(blank=True, default=1, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sms.smsautomation')),
            ],
            options={
                'verbose_name': 'Automation',
                'verbose_name_plural': 'Automations',
            },
        ),
        migrations.CreateModel(
            name='SMSCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('sender', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
            },
        ),
        migrations.CreateModel(
            name='SMSList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'List',
                'verbose_name_plural': 'Lists',
            },
        ),
        migrations.CreateModel(
            name='SMSListData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('is_valid', models.BooleanField(blank=True, default=False, null=True)),
                ('list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.smslist')),
            ],
            options={
                'verbose_name': 'List Data',
                'verbose_name_plural': 'List Data',
            },
        ),
        migrations.CreateModel(
            name='SMSCampaignOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(blank=True, default=1, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='sms.smscampaign')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offer.offer')),
            ],
            options={
                'verbose_name': 'Campaign Offer',
                'verbose_name_plural': 'Campaign Offers',
            },
        ),
        migrations.AddField(
            model_name='smscampaign',
            name='lists',
            field=models.ManyToManyField(to='sms.smslist'),
        ),
        migrations.CreateModel(
            name='SMSAutomationTextAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('automation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_ads', to='sms.smsautomation')),
            ],
            options={
                'verbose_name': 'Automation Ad',
                'verbose_name_plural': 'Automation Ads',
            },
        ),
        migrations.CreateModel(
            name='SMSAdText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, default=1, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_texts', to='sms.smscampaign')),
            ],
            options={
                'verbose_name': 'Ad Text',
                'verbose_name_plural': 'Ad Texts',
            },
        ),
        migrations.CreateModel(
            name='SMSAutomationCampaign',
            fields=[
            ],
            options={
                'verbose_name': 'Automation',
                'verbose_name_plural': 'Automation',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sms.smscampaign',),
        ),
        migrations.AddField(
            model_name='smsautomation',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='sms.smsautomationcampaign'),
        ),
    ]
