# Generated by Django 4.2.3 on 2024-02-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_distribution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiser',
            name='active',
        ),
        migrations.AddField(
            model_name='advertiser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
