# Generated by Django 4.2.3 on 2024-02-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_distribution', '0002_remove_advertiser_active_advertiser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
