# Generated by Django 4.2.3 on 2024-02-22 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_distribution', '0003_provider_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rotationcontrol',
            old_name='is_enabled',
            new_name='is_active',
        ),
    ]
