# Generated by Django 4.2.3 on 2024-02-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_distribution', '0004_rename_is_enabled_rotationcontrol_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotationcontrol',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
