# Generated by Django 4.2.3 on 2024-02-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_distribution', '0005_alter_rotationcontrol_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rotationcontrolcountryfolder',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='rotationcontrolcountrysplitfolder',
            name='countries',
        ),
    ]
