# Generated by Django 4.2.3 on 2023-07-25 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliate', '0002_initial'),
        ('leads_conversions', '0001_initial'),
        ('traffic_distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenueadvertiserfolder',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic_distribution.advertiser'),
        ),
        migrations.AddField(
            model_name='payoutaffiliatefolder',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate.affiliate'),
        ),
        migrations.AddField(
            model_name='payoutadvertiserfolder',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic_distribution.advertiser'),
        ),
    ]
