# Generated by Django 4.2.3 on 2024-02-22 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads_conversions', '0003_alter_payoutfolder_value_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payouts',
            old_name='is_enabled',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='revenues',
            old_name='is_enabled',
            new_name='is_active',
        ),
    ]
