# Generated by Django 4.2.3 on 2024-02-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_conversions', '0004_rename_is_enabled_payouts_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payouts',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='revenues',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
