# Generated by Django 4.2.3 on 2024-02-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads_conversions', '0005_alter_payouts_is_active_alter_revenues_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payoutcountryfolder',
            options={'verbose_name': 'Folder', 'verbose_name_plural': 'Folders'},
        ),
        migrations.AlterModelOptions(
            name='revenuecountryfolder',
            options={'verbose_name': 'Folder', 'verbose_name_plural': 'Folders'},
        ),
        migrations.RemoveField(
            model_name='payoutcountryfolder',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='revenuecountryfolder',
            name='countries',
        ),
    ]
