# Generated by Django 4.2.3 on 2024-01-16 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30, verbose_name='Company Name')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('telegram', models.CharField(blank=True, max_length=30, verbose_name='Telegram Username')),
                ('skype', models.CharField(blank=True, max_length=30, verbose_name='Skype Username')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfiles',
            },
        ),
    ]
