# Generated by Django 4.2.3 on 2024-01-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='first', max_length=30, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='last', max_length=30, verbose_name='Last name'),
        ),
    ]
