# Generated by Django 4.2.3 on 2023-07-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('speed_limit', models.IntegerField(blank=True, choices=[(5, 'Five'), (10, 'Ten'), (100, 'Hundred'), (1000, 'Thousand'), (10000, 'Ten Thousand'), (100000, 'Hundred Thousand')], default=5, help_text='How many emails can be sent per hour', null=True)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Email Server',
                'verbose_name_plural': 'Email Servers',
            },
        ),
    ]
