# Generated by Django 4.2.3 on 2023-12-06 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='summarized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ConversationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='chatgpt.conversation')),
            ],
            options={
                'verbose_name_plural': 'Conversation Summaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
