# Generated by Django 4.2.3 on 2023-12-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0003_message_summarized_at_conversationsummary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='content',
        ),
    ]
