# Generated by Django 4.2.3 on 2023-07-25 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0001_initial'),
        ('settings', '0001_initial'),
        ('traffic_distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='advertiser',
            field=models.ForeignKey(blank=True, help_text='Default advertiser for this offer.', null=True, on_delete=django.db.models.deletion.CASCADE, to='traffic_distribution.advertiser'),
        ),
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category for this offer.', null=True, on_delete=django.db.models.deletion.CASCADE, to='offer.offercategory'),
        ),
        migrations.AddField(
            model_name='offer',
            name='lead_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.form'),
        ),
    ]
