# Generated by Django 4.2.3 on 2023-07-25 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0001_initial'),
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='offer.offer', verbose_name='Offer'),
        ),
    ]
