# Generated by Django 4.2.3 on 2023-07-25 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trafficdata', '0001_initial'),
        ('affiliate', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliaterequestlog',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_request_logs', to='trafficdata.trafficdata'),
        ),
        migrations.AddField(
            model_name='affiliaterequestlog',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_logs', to='affiliate.apitoken'),
        ),
    ]
