# Generated by Django 4.2.3 on 2024-01-29 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliate',
            name='status',
        ),
    ]
