# Generated by Django 4.2.3 on 2024-02-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0006_affiliate_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ipwhitelist',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP Address'),
        ),
    ]
