# Generated by Django 4.2.3 on 2024-01-21 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_distribution', '0001_initial'),
        ('affiliate', '0004_initial'),
        ('trafficdata', '0002_alter_conversion_payout_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficdata',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trafficdata', to='traffic_distribution.advertiser', verbose_name='Advertiser'),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trafficdata', to='affiliate.affiliate', verbose_name='Affiliate'),
        ),
    ]
