# Generated by Django 4.2.3 on 2024-02-15 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crmterm',
            old_name='format',
            new_name='type',
        ),
    ]
