# Generated by Django 4.2.3 on 2024-02-22 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_rename_format_crmterm_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskmanagement',
            old_name='is_enabled',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='smsmanagement',
            old_name='is_enabled',
            new_name='is_active',
        ),
    ]
