# Generated by Django 4.2.3 on 2024-02-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_riskmanagement_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskmanagementcountryfolder',
            options={'verbose_name': 'Folder', 'verbose_name_plural': 'Folders'},
        ),
        migrations.AlterModelOptions(
            name='smscountryfolder',
            options={'verbose_name': 'Folder', 'verbose_name_plural': 'Folders'},
        ),
        migrations.RemoveField(
            model_name='riskmanagementcountryfolder',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='smscountryfolder',
            name='countries',
        ),
    ]
